mod descriptions;
mod fractal_conf;
mod fractal_data;
mod fractal_generator;
mod julia;
mod mandelbrot;
mod simple_variants;
pub use self::fractal_conf::*;
pub use self::fractal_data::*;
pub use self::fractal_generator::AlgebraElement;
pub use self::julia::*;
pub use self::mandelbrot::*;
pub use self::simple_variants::*;
